### PR TITLE
Support for 50/60Hz filter selection

### LINKED ISSUE #11: 50Hz/60Hz Noise Rejection Filter Selection set to default only
In MAX31856 there is 50Hz/60Hz noise rejection filter selection bit (bit 0 CR0 register). It is set by library to default (60 Hz) value - not usable for European countries. For 50 Hz noise rejection it has to be set to 1.

### PR DESCRIPTION
**Pull request by hjf**
Support for 50/60Hz filter selection
Fixes #11

### CODE REVIEW

**Comment by ladyada** [comment]
hiya thank you for the PR - we just added documentation (doxygen) to the repository, could you rebase and add it too? it would be greatly appreciated and make the library easier to use with your update :)

**Comment by hjf** [comment]
@ladyada done. I hope I did it right!

**Comment by ladyada** [comment]
looks good - lets see what travis says :)

**Comment by hjf** [comment]
It did catch a stupid mistake! But it's failing for an unrelated reason now.

**Comment by ladyada** [comment]
@hjf ok i had to delete the cache, theres one more thing to document - pretty easy tho. 
https://travis-ci.org/adafruit/Adafruit_MAX31856/builds/457094485

**Comment by ladyada** [comment]
thankx!

**Pull request merged**
